/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import View.CadastroPaciente;
import View.CadastroMedico;
import View.Agendamento;
/**
 *
 * @author Alexm
 */
public class TelaPrincipal extends javax.swing.JFrame {

     private CadastroMedico objetocadm;
     private CadastroPaciente objetocadp;
     
     private Agendamento objetoage;
        
    public TelaPrincipal() {
        initComponents();
      this.objetocadm = new CadastroMedico();
      this.objetocadp = new CadastroPaciente();
     
      this.objetoage = new Agendamento();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_cpaciente = new javax.swing.JButton();
        b_cmedicos = new javax.swing.JButton();
        b_agendamentos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Tela Inicial");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_cpaciente.setBackground(new java.awt.Color(0, 204, 153));
        b_cpaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        b_cpaciente.setForeground(new java.awt.Color(255, 255, 255));
        b_cpaciente.setText("PACIENTES");
        b_cpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cpacienteActionPerformed(evt);
            }
        });
        getContentPane().add(b_cpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 178, -1));

        b_cmedicos.setBackground(new java.awt.Color(0, 204, 153));
        b_cmedicos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        b_cmedicos.setForeground(new java.awt.Color(255, 255, 255));
        b_cmedicos.setText("MÉDICOS");
        b_cmedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cmedicosActionPerformed(evt);
            }
        });
        getContentPane().add(b_cmedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 178, -1));

        b_agendamentos.setBackground(new java.awt.Color(0, 204, 153));
        b_agendamentos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        b_agendamentos.setForeground(new java.awt.Color(255, 255, 255));
        b_agendamentos.setText("AGENDAMENTOS");
        b_agendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agendamentosActionPerformed(evt);
            }
        });
        getContentPane().add(b_agendamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 178, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/medicina3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cpacienteActionPerformed
      objetocadp.setVisible(true);
    }//GEN-LAST:event_b_cpacienteActionPerformed

    private void b_cmedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cmedicosActionPerformed
        objetocadm.setVisible(true);
    }//GEN-LAST:event_b_cmedicosActionPerformed

    private void b_agendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agendamentosActionPerformed
      objetoage.setVisible(true);
    }//GEN-LAST:event_b_agendamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_agendamentos;
    private javax.swing.JButton b_cmedicos;
    private javax.swing.JButton b_cpaciente;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
